# Generated by Django 4.2.1 on 2023-06-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0002_product_product_price_alter_product_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Ürünün fotoğrafı'),
        ),
    ]
