# Generated by Django 4.2.1 on 2023-06-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0004_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKozmetik.categories', verbose_name='Kategorisi'),
        ),
    ]
