# Generated by Django 4.2.1 on 2023-06-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorys',
        ),
    ]
