# Generated by Django 4.2.1 on 2023-06-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0006_rename_category_product_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorys',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKozmetik.categories', verbose_name='categories'),
        ),
    ]
