# Generated by Django 4.2.1 on 2023-06-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0009_remove_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_comment',
        ),
    ]
