# Generated by Django 4.2.1 on 2023-06-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0010_remove_comment_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKozmetik.product', verbose_name=''),
        ),
    ]
