# Generated by Django 4.2.1 on 2023-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0011_comment_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih ve saat'),
        ),
    ]
