# Generated by Django 4.2.1 on 2023-06-11 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0012_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saat'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Tarih ve saat'),
        ),
    ]
