# Generated by Django 4.2.1 on 2023-06-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0016_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='adet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adet'),
        ),
    ]
